package org.solarvillage.orderpermit;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("New Order")
@org.kie.api.definition.type.Description("Installation request information. Required to follow the permit requests.")
public class NewOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Beneficiary Full Name")
   private java.lang.String beneficiary;
   @org.kie.api.definition.type.Label(value = "Address")
   private java.lang.String address;
   @org.kie.api.definition.type.Label(value = "Approved")
   private java.lang.Boolean approved;

   public NewOrder()
   {
   }

   public java.lang.String getBeneficiary()
   {
      return this.beneficiary;
   }

   public void setBeneficiary(java.lang.String beneficiary)
   {
      this.beneficiary = beneficiary;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.Boolean getApproved()
   {
      return this.approved;
   }

   public void setApproved(java.lang.Boolean approved)
   {
      this.approved = approved;
   }

   public NewOrder(java.lang.String beneficiary, java.lang.String address,
         java.lang.Boolean approved)
   {
      this.beneficiary = beneficiary;
      this.address = address;
      this.approved = approved;
   }

}