//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 11:18:37 AM MDT 
//

package gov.services.permits.electrical;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.services.permits.PermitRequest;

/**
 * <p>
 * Java class for electricalPermitRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="electricalPermitRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://services.gov/permits}permitRequest">
 *       &lt;sequence>
 *         &lt;element name="contractNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "electricalPermitRequest", propOrder = { "contractNumber" })
public class ElectricalPermitRequest extends PermitRequest {

	@XmlElement(required = true)
	protected String contractNumber;

	/**
	 * Gets the value of the contractNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContractNumber() {
		return contractNumber;
	}

	/**
	 * Sets the value of the contractNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContractNumber(String value) {
		this.contractNumber = value;
	}

	@Override
	public String toString() {
		return "ElectricalPermitRequest [contractNumber=" + contractNumber + ", beneficiary=" + beneficiary
				+ ", address=" + address + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((contractNumber == null) ? 0 : contractNumber.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		ElectricalPermitRequest other = (ElectricalPermitRequest) obj;
		if (contractNumber == null) {
			if (other.contractNumber != null)
				return false;
		} else if (!contractNumber.equals(other.contractNumber))
			return false;
		return true;
	}

}
