//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 05:27:50 PM MDT 
//


package gov.services.permits.electrical;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.services.permits.electrical package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.services.permits.electrical
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RaiseElectricalPermitRequest }
     * 
     */
    public RaiseElectricalPermitRequest createRaiseElectricalPermitRequest() {
        return new RaiseElectricalPermitRequest();
    }

    /**
     * Create an instance of {@link RescindElectricalPermitRequest }
     * 
     */
    public RescindElectricalPermitRequest createRescindElectricalPermitRequest() {
        return new RescindElectricalPermitRequest();
    }

    /**
     * Create an instance of {@link ElectricalPermitStatusResponse }
     * 
     */
    public ElectricalPermitStatusResponse createElectricalPermitStatusResponse() {
        return new ElectricalPermitStatusResponse();
    }

    /**
     * Create an instance of {@link RaiseElectricalPermitResponse }
     * 
     */
    public RaiseElectricalPermitResponse createRaiseElectricalPermitResponse() {
        return new RaiseElectricalPermitResponse();
    }

    /**
     * Create an instance of {@link RescindElectricalPermitResponse }
     * 
     */
    public RescindElectricalPermitResponse createRescindElectricalPermitResponse() {
        return new RescindElectricalPermitResponse();
    }

    /**
     * Create an instance of {@link ElectricalPermitStatusRequest }
     * 
     */
    public ElectricalPermitStatusRequest createElectricalPermitStatusRequest() {
        return new ElectricalPermitStatusRequest();
    }

    /**
     * Create an instance of {@link PermitDetailsRequest }
     * 
     */
    public PermitDetailsRequest createPermitDetailsRequest() {
        return new PermitDetailsRequest();
    }

}
