//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 09:29:49 PM MDT 
//


package gov.services.permits.structural;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import gov.services.permits.PermitResponse;
import gov.services.permits.PermitStatusRequest;
import gov.services.permits.PermitStatusResponse;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.services.permits.structural package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StructuralPermitRescindResponse_QNAME = new QName("http://services.gov/permits/structural", "structuralPermitRescindResponse");
    private final static QName _RaiseStructuralPermitResponse_QNAME = new QName("http://services.gov/permits/structural", "raiseStructuralPermitResponse");
    private final static QName _StructuralPermitStatusRequest_QNAME = new QName("http://services.gov/permits/structural", "structuralPermitStatusRequest");
    private final static QName _StructuralPermitRescindRequest_QNAME = new QName("http://services.gov/permits/structural", "structuralPermitRescindRequest");
    private final static QName _StructuralPermitStatusResponse_QNAME = new QName("http://services.gov/permits/structural", "structuralPermitStatusResponse");
    private final static QName _RaiseStructuralPermitRequest_QNAME = new QName("http://services.gov/permits/structural", "raiseStructuralPermitRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.services.permits.structural
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StructuralPermitRequest }
     * 
     */
    public StructuralPermitRequest createStructuralPermitRequest() {
        return new StructuralPermitRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermitResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.gov/permits/structural", name = "structuralPermitRescindResponse")
    public JAXBElement<PermitResponse> createStructuralPermitRescindResponse(PermitResponse value) {
        return new JAXBElement<PermitResponse>(_StructuralPermitRescindResponse_QNAME, PermitResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermitResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.gov/permits/structural", name = "raiseStructuralPermitResponse")
    public JAXBElement<PermitResponse> createRaiseStructuralPermitResponse(PermitResponse value) {
        return new JAXBElement<PermitResponse>(_RaiseStructuralPermitResponse_QNAME, PermitResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermitStatusRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.gov/permits/structural", name = "structuralPermitStatusRequest")
    public JAXBElement<PermitStatusRequest> createStructuralPermitStatusRequest(PermitStatusRequest value) {
        return new JAXBElement<PermitStatusRequest>(_StructuralPermitStatusRequest_QNAME, PermitStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermitStatusRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.gov/permits/structural", name = "structuralPermitRescindRequest")
    public JAXBElement<PermitStatusRequest> createStructuralPermitRescindRequest(PermitStatusRequest value) {
        return new JAXBElement<PermitStatusRequest>(_StructuralPermitRescindRequest_QNAME, PermitStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermitStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.gov/permits/structural", name = "structuralPermitStatusResponse")
    public JAXBElement<PermitStatusResponse> createStructuralPermitStatusResponse(PermitStatusResponse value) {
        return new JAXBElement<PermitStatusResponse>(_StructuralPermitStatusResponse_QNAME, PermitStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuralPermitRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.gov/permits/structural", name = "raiseStructuralPermitRequest")
    public JAXBElement<StructuralPermitRequest> createRaiseStructuralPermitRequest(StructuralPermitRequest value) {
        return new JAXBElement<StructuralPermitRequest>(_RaiseStructuralPermitRequest_QNAME, StructuralPermitRequest.class, null, value);
    }

}
