//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 11:18:37 AM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.gov/permits/structural", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.services.permits.structural;
